export const DOCTORS_REQUEST = "DOCTORS_REQUEST"
export const DOCTORS_FAILURE = "DOCTORS_FAILURE"

export const GET_DOCTORS = "GET_DOCTORS"
export const GET_USERS = "GET_USERS"

export const POST_USER = "POST_USER"